-- ============================================================
-- Learning Logs Database — Sample Data (Week 5)
-- ============================================================
-- Run this file AFTER learninglog.sql to add sample data.
--
-- Changes from Week 4:
--   1. NEW: Insert a default user first (required before topics)
--   2. UPDATED: Topic inserts now include user_id column
--   3. entries — same as Week 4
--
-- NOTE: The password below is a BCrypt hash of "Test@123"
-- (generated by PasswordUtil.getHashPassword("Test@123"))
-- In a real app, passwords are NEVER stored as plaintext.
-- ============================================================

USE learning_logs;

-- Clear existing data before seeding
DELETE FROM entries;
DELETE FROM topics;
DELETE FROM users;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE topics AUTO_INCREMENT = 1;
ALTER TABLE entries AUTO_INCREMENT = 1;

-- ========== NEW for Week 5 ==========
-- Insert a default user (needed because topics now require user_id)
-- Password: "Test@123" → BCrypt hashed (you'll see a $2a$10$... string)
INSERT INTO users (username, email, password) VALUES
('testuser', 'test@example.com', '$2a$10$yUK8SPXB.NwRSviTxcIVHOxtfvwjGEe600j9g2H5xi3Y4l54A5jLa');

-- ========== UPDATED for Week 5 ==========
-- Topics now include user_id (all assigned to testuser, id=1)
-- Week 4 had: INSERT INTO topics (name) VALUES (...)
-- Week 5 has: INSERT INTO topics (name, user_id) VALUES (..., 1)
INSERT INTO topics (name, user_id) VALUES
('Python', 1),
('Web Development', 1),
('Data Science', 1),
('Machine Learning', 1),
('Cybersecurity', 1);

-- ========== Same as Week 4 ==========
-- Sample entries (unchanged — still reference topic_id)
INSERT INTO entries (topic_id, title, text, link, image) VALUES
(1, 'Variables and Data Types', 'Python uses dynamic typing. Variables do not need explicit type declarations.', 'https://docs.python.org/3/tutorial/introduction.html', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/800px-Python-logo-notext.svg.png'),
(1, 'Control Flow', 'if/elif/else statements and for/while loops are the main control flow tools.', NULL, NULL),
(2, 'HTML Basics', 'HTML provides the structure of a web page using elements and tags.', 'https://developer.mozilla.org/en-US/docs/Learn/HTML', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/800px-HTML5_logo_and_wordmark.svg.png'),
(2, 'CSS Flexbox', 'Flexbox is a one-dimensional layout method for arranging items in rows or columns.', 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/800px-CSS3_logo_and_wordmark.svg.png'),
(3, 'Introduction to Pandas', 'Pandas provides DataFrames for structured data analysis in Python.', 'https://pandas.pydata.org/docs/', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/800px-Pandas_logo.svg.png');
